#%RAML 1.0 NamedExample
value:
-
  ID: 123
  foodName: nonvegBiryani
  foodPrice: 250
  foodQnty: Two members
  foodSpicy: Yes
  foodRating: Five stars
-
  ID: 456
  foodName: vegBiryani
  foodPrice: 175
  foodQnty: Two members
  foodSpicy: Yes
  foodRating: Four stars